### ISSUE TITLE
How can I change json part so I can query by size, owner ?

### ISSUE THREAD

**Issue by ibmamnt** [denyeart/table_to_json#1]
Even though I modified the compound key in init_marble_json() such that:

``` // Convert marble to JSON with Color and Name as compound key
  compoundKey, _ := t.createCompoundKey(objectType, []string{marble.Color, marble.Name, strconv.Itoa(marble.Size), marble.Owner})
  marbleJSONBytes, _ := json.Marshal(marble)```

I can not query by owner, the query result empty. I can query by "blue", since this is the first key, but second key like "Name", "Size" or "Owner" fails.

How can I handle these partial query in this sample code ?

I'm using fabric v0.6.1, since this version is deployed on IBM  Bluemix service.

**Comment by denyeart** [comment]
You would have to create another composite key starting with owner, if you want to query on owner, using a 2nd objectType. See a more complete example with comments in the v1 example: https://github.com/hyperledger/fabric/blob/master/examples/chaincode/go/marbles02/marbles_chaincode.go.  You could do similar with custom chaincode in 0.6.

**Comment by ibmamnt** [comment]
Thanks for the clarification. I understood now.
